SET LINESIZE 140
COL USERNAME FORMAT A20
SELECT S.SID, S.SERIAL#, S.USERNAME, S.STATUS, S.LOGON_TIME,
ROUND((SYSDATE - S.LOGON_TIME) * 24 * 60, 2) AS "Session Duration (Minutes)"
FROM V$SESSION S WHERE S.SID = &SID AND S.SERIAL# = &SERIAL
AND type <> 'BACKGROUND'
/
