COLUMN BEGIN_TIMESTAMP NEW_VALUE A
SELECT to_char(sysdate,'YYYY-MM-DD HH24:MI:SS') AS BEGIN_TIMESTAMP
FROM DUAL ;

exec dbms_lock.sleep(10);


COLUMN END_TIMESTAMP NEW_VALUE B
SELECT to_char(sysdate,'YYYY-MM-DD HH24:MI:SS') AS END_TIMESTAMP
FROM DUAL ;

COL DURATION NEW_VALUE C
SELECT (to_date('&B', 'YYYY-MM-DD HH24:MI:SS') - to_date('&A','YYYY-MM-DD HH24:MI:SS')) * 24 * 60 * 60 AS DURATION
FROM DUAL;

PROMPT The script took &C seconds to run
